"""Database adapter. Render requires PostgreSQL; SQLite is for local use only."""
import os
import sqlite3
import psycopg
from psycopg.rows import dict_row

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
IntegrityError = (sqlite3.IntegrityError, psycopg.IntegrityError)
TABLES = {
    'users': 'username TEXT UNIQUE,password TEXT,name TEXT,active INTEGER DEFAULT 1,force_password_change INTEGER DEFAULT 0,role TEXT DEFAULT \'user\'',
    'campaigns': "name TEXT,title TEXT,prize TEXT,draw_at TEXT,terms TEXT,image TEXT DEFAULT '',active INTEGER DEFAULT 0,created_at TEXT",
    'participants': 'campaign_id INTEGER,name TEXT,whatsapp TEXT,email TEXT,company TEXT,created_at TEXT,winner INTEGER DEFAULT 0,allow_again INTEGER DEFAULT 1,blocked INTEGER DEFAULT 0,UNIQUE(campaign_id,email)',
    'draws': 'campaign_id INTEGER,drawn_at TEXT,winner_ids TEXT,operator TEXT',
    'audit_logs': 'user_id INTEGER,username TEXT,action TEXT,details TEXT,created_at TEXT',
}

class Row(dict):
    def __getitem__(self, key):
        return list(self.values())[key] if isinstance(key, int) else super().__getitem__(key)

class Cursor:
    def __init__(self, cursor):
        self.cursor = cursor
    def fetchone(self):
        row = self.cursor.fetchone()
        return Row(row) if row is not None else None
    def fetchall(self):
        return [Row(row) for row in self.cursor.fetchall()]

class Postgres:
    def __init__(self, url):
        self.connection = psycopg.connect(url, row_factory=dict_row, connect_timeout=10)
    def execute(self, sql, params=()):
        # Application queries use ? placeholders and contain no literal question marks.
        return Cursor(self.connection.execute(sql.replace('?', '%s'), params))
    def commit(self):
        self.connection.commit()
    def rollback(self):
        self.connection.rollback()
    def close(self):
        self.connection.close()

def connect(path):
    if DATABASE_URL:
        return Postgres(DATABASE_URL)
    if os.getenv('RENDER') == 'true':
        raise RuntimeError('DATABASE_URL obrigatória no Render; SQLite efêmero desabilitado.')
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    return connection

def create_schema(connection):
    postgres = isinstance(connection, Postgres)
    if postgres:
        # Serialize schema and bootstrap across Gunicorn workers.
        connection.execute('SELECT pg_advisory_xact_lock(72631008)')
    identity = 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if postgres else 'INTEGER PRIMARY KEY'
    for table, columns in TABLES.items():
        connection.execute(f'CREATE TABLE IF NOT EXISTS {table}(id {identity},{columns})')
    if postgres:
        connection.execute('ALTER TABLE users ADD COLUMN IF NOT EXISTS force_password_change INTEGER DEFAULT 0')
        connection.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user'")
    else:
        columns = [r['name'] for r in connection.execute('PRAGMA table_info(users)').fetchall()]
        if 'force_password_change' not in columns:
            connection.execute('ALTER TABLE users ADD COLUMN force_password_change INTEGER DEFAULT 0')
        if 'role' not in columns:
            connection.execute("ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'user'")
    connection.execute('CREATE INDEX IF NOT EXISTS participants_campaign_idx ON participants(campaign_id)')
    connection.execute('CREATE INDEX IF NOT EXISTS draws_campaign_idx ON draws(campaign_id)')

def insert_campaign(connection, values):
    sql = 'INSERT INTO campaigns(name,title,prize,terms,image,active,created_at) VALUES(?,?,?,?,?,?,?)'
    if isinstance(connection, Postgres):
        return connection.execute(sql + ' RETURNING id', values).fetchone()['id']
    return connection.execute(sql, values).lastrowid
